### PR TITLE
CI setup 

### PR DESCRIPTION
**Pull request by ghanatava**
Created a workflow to build docker image of the application and publish onto docker hub.
Created a Dockerfile to containerize the fastapi app.

### CODE REVIEW

**Comment by ghanatava** [comment]
@Mr-Sunglasses  review it.

**Comment by Mr-Sunglasses** [comment]
@ghanatava PLEASE add a compose-file to setup local db for psql

**Comment by ghanatava** [comment]
Okk I will do it.

**Comment by ghanatava** [comment]
added docker-compose @Mr-Sunglasses  please review it

**Pull request closed without merging**
